### ISSUE TITLE
Antag rounds played is always the same as rounds played

### ISSUE THREAD

**Issue by Simyon264** [Simyon264/ReplayBrowser#29]
![image](https://github.com/user-attachments/assets/b16bc96b-6f50-4251-83a6-bb6ca2ac3f72)
![image](https://github.com/user-attachments/assets/a0bc93a4-a989-4355-aaa1-56d6337502e1)
![image](https://github.com/user-attachments/assets/cbbe0e73-7250-4078-b775-11fdae79969d)

**Comment by SaphireLattice** [comment]
Oops

Might have messed up a query somewhere...
