### ISSUE TITLE
Add Grimbly

### ISSUE THREAD

**Issue by flyingkarii** [Simyon264/ReplayBrowser#64]
Caddy, raw file listing.
https://replays.grimbly.net/grimble/

I'm the owner of Grimbly Station, you can verify in the discord: https://grimbly.net/discord

**Comment by Simyon264** [comment]
Hey!

I see in the replay_final.yml files that the server id and server name are both not set. What would they be?
```yml
server_id: unknown_server_id
server_name: unknown
```

**Comment by flyingkarii** [comment]
Oh, yeah that's my bad, I'll set them now.
If both are meant to be unique, just do "Grimbly" for both.

**Comment by Simyon264** [comment]
I've also noticed that the replays dont run from the launcher...? They are missing the required content bundle file. 
Though thats not a requirement for a listing on the replay browser.

**Comment by flyingkarii** [comment]
Yeah, we don't have a CDN yet but I plan to fix that. Here's hoping it actually works this time.
