### ISSUE TITLE
Add Funky Station

### ISSUE THREAD

**Issue by taydeo** [Simyon264/ReplayBrowser#65]
Heya! Not sure if this is the proper place to do it, so apologies in advance.

I'm the owner of Funky Station, and we'd love to get our replays up.

https://replays.funkystation.org/lrp1/
https://replays.funkystation.org/mrp1/

Both are served with NGINX. Feel free to contact me through this or on our Discord at https://discord.gg/funky14

**Comment by Simyon264** [comment]
This is indeed the correct place! I'll get this sorted once I wake up.
