### ISSUE TITLE
File size is incorrect

### ISSUE THREAD

**Issue by NullWanderer** [Simyon264/ReplayBrowser#8]
Here's one Delta replay
![image](https://github.com/Simyon264/ReplayBrowser/assets/56081759/20d754e8-d902-4739-9145-0951b523aea9)
Our own replay viewer puts this file at 376mb, not 1gb
![image](https://github.com/Simyon264/ReplayBrowser/assets/56081759/476de780-e5bb-4874-947c-16107b0163a3)
Its the only one I checked, but I assume you're maybe checking the uncompressed size instead of the actual .zip file?

**Comment by Simyon264** [comment]
Yeah, the size is the uncompressed one. Will fix by also displaying the compressed size.

**Comment by Simyon264** [comment]
Fixed in https://github.com/Simyon264/ReplayBrowser/commit/472982638a0367edb9906fec6893279dd75e7091
